### ISSUE TITLE
[Feat] Variable 사용성 개선

### ISSUE THREAD

**Issue by GangBean** [GangBean/dezero#13]
## Background
- Variable의 사용성을 개선하기 위해 변수별 구분, 변수 데이터 특성 확인 등을 위한 장치를 추가한다.
- 여러가지 변수를 구분하기 위해, 변수에 이름 속성을 추가한다.
- 변수가 담고있는 데이터의 shape, ndim, len 등을 알 수 있도록 기능을 추가한다.
- 변수의 정보를 가시성있게 출력할 수 있도록 기능을 추가한다.

## Todo
- [x] Variable 에 name속성 추가
- [x] Variable 에 shape, ndim, size, dtype @property 메소드 추가
- [x] Varibale 의 __len__, __repr__ 메소드 구현
